apiVersion: v1
kind: Service
metadata:
  name: vprodb
spec:
  ports:
    - port: 3306
      targetPort: 3306 # Assuming the container port is also 3306
      protocol: TCP
  selector:
    app: vprodb
  type: ClusterIP
